/// Every package in the template's resolved dependency graph, including the
/// ones the workspace only depends on indirectly (for example `bloc`, through
/// `flutter_bloc`). The app package cannot take any of these names: pub would
/// fail to resolve the workspace, after the initializer already ran.
///
/// The initializer runs before `melos bootstrap`, when there is no
/// `pubspec.lock` to read (it is git-ignored), so the names are listed here.
/// A test fails when a dependency change adds a package that is missing; add
/// the names it reports.
const resolvedPackageNames = <String>{
  '_fe_analyzer_shared',
  'analyzer',
  'ansi_styles',
  'app_links',
  'app_links_linux',
  'app_links_platform_interface',
  'app_links_web',
  'archive',
  'args',
  'async',
  'bloc',
  'bloc_test',
  'boolean_selector',
  'build',
  'build_config',
  'build_daemon',
  'build_runner',
  'built_collection',
  'built_value',
  'characters',
  'charcode',
  'checked_yaml',
  'cli_config',
  'cli_launcher',
  'cli_util',
  'clock',
  'collection',
  'color',
  'conventional_commit',
  'convert',
  'coverage',
  'crypto',
  'csslib',
  'cupertino_icons',
  'cupertino_ui',
  'dart_style',
  'dartx',
  'diff_match_patch',
  'dio',
  'dio_web_adapter',
  'equatable',
  'fake_async',
  'ffi',
  'ffi_leak_tracker',
  'file',
  'firebase_core',
  'firebase_core_platform_interface',
  'firebase_core_web',
  'fixnum',
  'flutter',
  'flutter_bloc',
  'flutter_dotenv',
  'flutter_gen',
  'flutter_gen_core',
  'flutter_lints',
  'flutter_localizations',
  'flutter_svg',
  'flutter_test',
  'flutter_web_plugins',
  'frontend_server_client',
  'gap',
  'get_it',
  'glob',
  'go_router',
  'graphs',
  'gtk',
  'hashcodes',
  'html',
  'http',
  'http_multi_server',
  'http_parser',
  'image',
  'image_size_getter',
  'intl',
  'intl_utils',
  'io',
  'json_annotation',
  'leak_tracker',
  'leak_tracker_flutter_testing',
  'leak_tracker_testing',
  'lints',
  'logging',
  'matcher',
  'material_color_utilities',
  'material_ui',
  'melos',
  'meta',
  'mime',
  'mocktail',
  'mustache_template',
  'nested',
  'node_preamble',
  'package_config',
  'package_info_plus',
  'package_info_plus_platform_interface',
  'path',
  'path_parsing',
  'path_provider_linux',
  'path_provider_platform_interface',
  'path_provider_windows',
  'permission_handler',
  'permission_handler_android',
  'permission_handler_apple',
  'permission_handler_html',
  'permission_handler_platform_interface',
  'permission_handler_windows',
  'petitparser',
  'platform',
  'plugin_platform_interface',
  'pool',
  'posix',
  'process',
  'prompts',
  'provider',
  'pub_semver',
  'pub_updater',
  'pubspec_parse',
  'shared_preferences',
  'shared_preferences_android',
  'shared_preferences_foundation',
  'shared_preferences_linux',
  'shared_preferences_platform_interface',
  'shared_preferences_web',
  'shared_preferences_windows',
  'shelf',
  'shelf_packages_handler',
  'shelf_static',
  'shelf_web_socket',
  'sky_engine',
  'source_map_stack_trace',
  'source_maps',
  'source_span',
  'stack_trace',
  'stream_channel',
  'stream_transform',
  'string_scanner',
  'term_glyph',
  'test',
  'test_api',
  'test_core',
  'time',
  'typed_data',
  'universal_html',
  'universal_io',
  'vector_graphics',
  'vector_graphics_codec',
  'vector_graphics_compiler',
  'vector_math',
  'vm_service',
  'watcher',
  'web',
  'web_socket',
  'web_socket_channel',
  'webkit_inspection_protocol',
  'win32',
  'xdg_directories',
  'xml',
  'yaml',
  'yaml_edit',
};

/// Reads the package names from the contents of a `pubspec.lock`.
Set<String> lockedPackageNames(String lock) {
  final names = <String>{};
  final topLevelKey = RegExp(r'^[a-z_]+:');
  final packageKey = RegExp(r'^  ([a-z0-9_]+):\s*$');
  var inPackages = false;
  for (final line in lock.split('\n')) {
    if (topLevelKey.hasMatch(line)) {
      inPackages = line.startsWith('packages:');
      continue;
    }
    final package = packageKey.firstMatch(line.trimRight());
    if (inPackages && package != null) names.add(package.group(1)!);
  }
  return names;
}
