name: one_time_chat

packages:
  - app
  - modules/*

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.
  analyze:
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.
  pub:get:
    exec: flutter pub get
    description: Run `flutter pub get` in selected or all packages. Includes prompt for packages.
    packageFilters:
      dirExists:
        - lib
  pub:runner:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    description: Run ` pub run build_runner` in selected or all packages. Includes prompt for packages.
    packageFilters:
      dirExists:
        - lib
  pub:upgrade:
    exec: flutter pub upgrade
    description: Run `dart pub upgrade` in selected or all packages. Includes prompt for packages.
    packageFilters:
      dirExists:
        - lib
  doctor:
    exec: flutter doctor
    description: Run `dart doctor` in selected or all packages. Includes prompt for packages.
    packageFilters:
      dirExists:
        - lib
